### PR TITLE
Allow use on VM

### PR DESCRIPTION
**Pull request by azenla**
This adds support for use on the VM

### CODE REVIEW

**Comment by logotype** [comment]
Hi, thanks for this! It's a lot of changes, so I have to look through this a bit before accepting the PR. Thanks!

**Comment by azenla** [comment]
It seems to work on the browser but not on the VM. Can you look into this for me? Seems it's not sending a header.

**Comment by azenla** [comment]
I just got it working with a little bit of experimentation :) Looks like it's actually an issue with LeapMotion's WebSocket Server

https://community.leapmotion.com/t/leapmotion-websocket-server-is-too-strict/2250/2

I have a workaround that is stable though

**Comment by azenla** [comment]
No Problem :)

**Pull request merged**
